Use the generated Signon API key in Whitehall
alphagov/govuk-helm-charts pull request #2864
Opened 2024-12-20 13:20 UTC by pezholio

All environemnts have a user “Signon API User” (eg https://signon.integration.publishing.service.gov.uk/api_users/18089/edit) which has access to the “Signon API” app. 

I've manually run the `signon-sync-token-secrets-to-k8s` cron job in all three environments, so these should be good to go!

2024-12-23 09:57 UTC, theseanything commented
Why Whitehall needs to access Signon's APIs? What feature does this relate too?

2025-01-06 09:22 UTC, pezholio commented
This relates to the newly-minted API endpoint https://github.com/alphagov/signon/pull/3426 that allows us to get users from a central source if truth. This requires a new API "user" that is set up for that endpoint only. It doesn't relate to the OAuth side of signon at all

2025-01-06 13:11 UTC, theseanything approved these changes

2025-01-06 13:11 UTC, theseanything requested changes
Can you roll this out to integration/staging first.

2025-01-06 13:14 UTC, theseanything approved these changes

2025-01-06 13:15 UTC, merged