Add tagging all images in every environment to the update-image-tag-workflow
alphagov/govuk-helm-charts pull request #562
Opened 2022-09-06 16:53 UTC by desenhar

2022-09-07 11:02 UTC, theseanything reviewed
Also just a reminder to tidy up your commits before putting this review: https://gds-way.cloudapps.digital/standards/source-code/working-with-git.html#commit-messages

2022-09-07 11:02 UTC, theseanything commented on charts/argo-workflows/scripts/update-image-tag.sh
> +  add_tag
We should only tag the image after we've successfully update the helm chart image tag value (on line 51).

2022-09-13 09:10 UTC, theseanything requested changes

2022-09-13 09:10 UTC, theseanything commented on .github/workflows/update-image-tag.yml
> +      ecr_registry:
If we aren't changing this value, as it's always production ECR - this doesn't need to be a workflow input from the GitHub. I.e. just put the value in the Argo Workflow - charts/argo-workflows/templates/update-image-tag.yaml:47

2022-09-13 09:10 UTC, theseanything commented on charts/argo-workflows/scripts/update-image-tag.sh
> +  current_image_tag="$IMAGE_TAG"
Why not just use IMAGE_TAG?

2022-09-13 09:10 UTC, theseanything commented on charts/argo-workflows/scripts/update-image-tag.sh
> +  aws ecr put-image --repository-name "${REPO_NAME}" --image-tag "deployed-to-production" --image-manifest "$MANIFEST"
We have to tag images being used in staging and integration also

```suggestion
  aws ecr put-image --repository-name "${REPO_NAME}" --image-tag "deployed-to-${ENVIRONMENT}" --image-manifest "$MANIFEST"
```

2022-09-13 09:10 UTC, theseanything commented on charts/argo-workflows/templates/update-image-tag.yaml
> +          - name: ecrRegistry
Doesn't need to be an input as we're not changing it per workflow run

2022-09-13 09:11 UTC, theseanything commented
> Also just a reminder to tidy up your commits before putting this review: https://gds-way.cloudapps.digital/standards/source-code/working-with-git.html#commit-messages

Can you also format the commit message as per the style guide and add in detail about why these changes?

2022-09-16 14:04 UTC, desenhar commented
The commit's have been squashed and one has been left with a description below justifying why this change was needed.

2022-09-20 10:24 UTC, theseanything approved these changes

2022-09-20 10:28 UTC, merged